Задание №1: Shell
LDVSOFT/spbau-term5-software-design pull request #1
Opened 2016-09-21 16:26 UTC by LDVSOFT

2016-09-25 15:59 UTC, LDVSOFT commented
@yurii-litvinov Я всё правильно сделал для отправки задания?

2016-09-25 16:28 UTC, yurii-litvinov commented
надо ещё на http://hwproj.me/ отметить, что Вы это сдали, а то я про Вас забыл, да :) спасибо, что напомнили.

2016-10-04 19:45 UTC, yurii-litvinov requested changes
- Лучше выкладывать не только .iml, но и всю папку .idea (кроме каких-то пары файлов, которые не надо), либо файл с конфигурацией сборки maven или gradle, а то прямо сходу оно не собирается.
- Диаграмма довольно ужасающа. Чего только стоит комментарий "Lexer is just scanning the input and cutting it in different rules. That's why it has s, i and n fields.", что я читаю примерно как "Это лексер, поэтому у него есть какие-то поля с однобуквенными именами, чо". И комментарии к классам отформатированы, будто они стихи :)

Вообще, почти всё хорошо, но диаграмму и мелкие замечания по коду поправьте, пожалуйста.

2016-10-04 19:45 UTC, yurii-litvinov commented on src/net/ldvsoft/spbau/Command.java
> +    static InputStream getInputStream(Shell shell, Path inputFile) throws IOException {
А чего эти методы без комментариев?

2016-10-04 19:45 UTC, yurii-litvinov commented on src/net/ldvsoft/spbau/Lexer.java
> +    private int i;
Имена полей не очень говорящие.

2016-10-04 19:45 UTC, yurii-litvinov commented on src/net/ldvsoft/spbau/Shell.java
> +    /*package*/ void work() {
Никогда не видел, чтобы /* package */ писали в виде комментария. Возможно, потому, что package-методы редко используются вообще (package-классы с public-методами решают ту же задачу и концептуально проще). Но вообще, всем же понятно, что они package, и раз это компилятором не проверяется, то нет особого смысла и комментарий писать.

2016-10-04 19:45 UTC, yurii-litvinov commented on src/net/ldvsoft/spbau/SyntaxError.java
> +public class SyntaxError extends Exception {
К этой штуке тоже нужен комментарий.

2016-10-05 09:14 UTC, LDVSOFT commented on src/net/ldvsoft/spbau/Shell.java
> +    /*package*/ void work() {
Нам такой codestyle рекомендовали на курсе Java. Могу убрать.

2016-10-05 11:23 UTC, yurii-litvinov commented on src/net/ldvsoft/spbau/Shell.java
> +    /*package*/ void work() {
Не, если рекомендовали, то не убирайте. Почему-то никто больше из Ваших коллег такому соглашению не следует :)

2016-10-09 12:41 UTC, LDVSOFT commented
@yurii-litvinov Про стихи на диаграмме -- оно само так)
Переделал схему, исправил замечания.
Жду ваших комментариев.

2016-10-14 09:09 UTC, yurii-litvinov commented
Так оно всё равно из коробки не собирается :) Может, лучше написать сборку, скажем, на Gradle, и выкладывать конфиги для него?

2016-10-14 09:12 UTC, yurii-litvinov commented
Ещё исходник диаграммы всё-таки надо выложить. С одной стороны это бинарник, но с другой стороны к нему можно относиться как к коду. Иначе поправить диаграмму будет нельзя.

2016-10-19 07:51 UTC, LDVSOFT commented
Hopefully this helps!

2016-11-05 18:16 UTC, yurii-litvinov approved these changes

2016-11-05 18:16 UTC, merged